### ISSUE TITLE
adicionar dados do Interruptor

### ISSUE THREAD

**Issue by aariops** [rgllm/awesome-portugal-data#17]
O Interruptor tem disponibilizado vários conjuntos de dados, focados sobretudo em cultura.

https://github.com/InterruptorPt/dados

Até fazia pull request, mas não sei bem onde preferem arrumar isto. :)

**Comment by rgllm** [comment]
Olá @aariops 👋
Podes fazer um PR para adicionar?

**Comment by rgllm** [comment]
Closed #18
