### ISSUE TITLE
taxas de aprovaçao IMT

### ISSUE THREAD

**Issue by fjsousa** [rgllm/awesome-portugal-data#22]
Como posso fazer um PR com estes dois repos:

https://github.com/codecadre/imt-pass-rates
https://github.com/codecadre/imt-school-addresses

**Comment by rgllm** [comment]
Olá @fjsousa 👋
Podes fazer fork a este repositório e depois abrir o PR a partir do fork. Caso precises de ajuda avisa.

Obrigado 🙂
