### ISSUE TITLE
Actualizar layout

### ISSUE THREAD

**Issue by ptalmeida** [rgllm/awesome-portugal-data#9]
Em especial para diferenciar entre APIs SOAP, REST, GRAPHQL; por exemplo:

- [FenixEdu IST](https://fenixedu.org/dev/api/) &mdash; API para a plataforma FenixEdu do IST. ![](https://img.shields.io/badge/API-REST-orange)
- [Feriados Portugueses](http://services.sapo.pt/Metadata/Contract/Holiday?culture=PT) &mdash; Lista de feriados nacionais, regionais e municipais. Suporta o cálculo dos feriados para os anos entre 1582 e 2299. ![](https://img.shields.io/badge/API-SOAP-red)

**Comment by rgllm** [comment]
@ptalmeida boa sugestão. Poderiamos aproveitar a oportunidade e mudar para algo mais escalável. Exemplo:

| API      | Descrição                                                                                                          | Tipo | Autenticação |
|----------|--------------------------------------------------------------------------------------------------------------------|------|--------------|
| [FenixEdu IST](https://fenixedu.org/dev/api/)    | API para a plataforma FenixEdu do IST                                                                              | REST | Não          |
| [Feriados Portugueses](http://services.sapo.pt/Metadata/Contract/Holiday?culture=PT) | Lista de feriados nacionais, regionais e municipais. Suporta o cálculo dos feriados para os anos entre 1582 e 2299 | SOAP | Não          |

O que te parece?

**Comment by ptalmeida** [comment]
Parece-me excelente!  
Iterando um pouco na ideia:

API | Descrição | Tipo | Autenticação
-- | -- | :----------------: | :-------------: |
[FenixEdu IST](https://fenixedu.org/dev/api) | API para a plataforma FenixEdu do IST | ![](https://img.shields.io/badge/REST-orange) | ✔️ | 
[Feriados Portugueses](http://services.sapo.pt/Metadata/Contract/Holiday?culture=PT) | Lista de feriados nacionais, regionais e municipais. Suporta o cálculo dos feriados para os anos entre 1582 e 2299 | ![](https://img.shields.io/badge/SOAP-red) | ❌ | 
[Lorem Ipsum](http://lorem.ipsum) | texto | ![](https://img.shields.io/badge/GraphQL-e535ab) | ✔️ | 
[Lorem Ipsum2](http://lorem.ipsum) | mais texto | ![](https://img.shields.io/badge/GraphQL-e535ab)  ![](https://img.shields.io/badge/SOAP-red) ![](https://img.shields.io/badge/SDK-yellow) | ✔️ | 

Penso que faltaria diferenciar também entre APIs e datasets públicos, talvez distribuídos em tabelas diferentes mas mantendo na mesma categoria para evitar repetição na tabela de conteúdos:

## Aveiro
API | Descrição | Tipo | Autenticação
-- | -- | :----------------: | :-------------: |
[Lorem Ipsum](http://lorem.ipsum) | texto | ![](https://img.shields.io/badge/GraphQL-e535ab) | ✔️ | 
[Lorem Ipsum2](http://lorem.ipsum) | mais texto | ![](https://img.shields.io/badge/GraphQL-e535ab)  ![](https://img.shields.io/badge/SOAP-red) ![](https://img.shields.io/badge/SDK-yellow) | ✔️ | 

Datasets | Descrição |
-- | -- |
[Lorem Ipsum](http://lorem.ipsum) | texto |
[Lorem Ipsum2](http://lorem.ipsum) | mais texto |

Que tal?

**Comment by ptalmeida** [comment]
Acrescento que penso que seria melhor organizar os dados por regiões **NUTS II** (ver abaixo), reduzindo a complexidade da tabela de conteúdos e sendo, na minha opinião, mais prático.  

Assim, por exemplo, um API exposto pela FCT UNL ficaiar na categoria **AML** e não na de **Setúbal**.

![](https://upload.wikimedia.org/wikipedia/commons/2/21/NUTS_PT_2013.png?1592484906579)

**Comment by rgllm** [comment]
Gosto das duas sugestões @ptalmeida. Adicionei-te como colaborador ao repositório para podermos trabalhar nisto de maneira mais eficiente.

**Comment by rgllm** [comment]
Tendo em conta a nova organização por regiões a minha sugestão seria:

- Europa
- Portugal
- Norte
- Centro
- Lisboa
- Alentejo
- Algarve
- Madeira
- Açores

E a migração seria:

- Aveiro -> Centro
- Braga -> Norte
- Porto -> Norte

**Comment by ptalmeida** [comment]
Obrigado! Então tomei a liberdade de criar um branch para irmos fazendo as alterações!
